apiVersion: v1
kind: Service
metadata:
  name: aop-be-app-cv1-sit-lb
  namespace: sit
  labels:
    app: aop-be-app-cv1-sit
    team: spring-boot-actuator
spec:
  type: LoadBalancer
  ports:
    - name: http
    - port: 8080
      targetPort: 8080
  selector:
    app: aop-be-app-cv1-sit
    team: spring-boot-actuator