apiVersion: v1
kind: Service
metadata:
  name: aop-be-app-cv1-sit-lb
  namespace: sit
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: aop-be-app-cv1-sit