apiVersion: apps/v1
kind: Deployment
metadata:
  name: aop-wms-rest
  namespace: __APP_ENV__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aop-wms-rest
  template:
    metadata:
      labels:
        app: aop-wms-rest
        team: spring-boot-actuator
    spec:
      containers:
        - name: aop-wms-rest
          image: __APP_REPO__
          ports:
            - containerPort: 8080
          env: 
            - name: APP_APIM_SUBSCRIPTIONKEY
              valueFrom:
                secretKeyRef:
                  name: secret-wms-apim
                  key: apim-secret
          resources:
            limits:
              cpu: '2'
              memory: 2G
            requests:
              cpu: 200m
              memory: 256M
              