apiVersion: v1
kind: Service
metadata:
  name: aop-wms-rest-service
  namespace: __APP_ENV__
  labels:
    app: aop-wms-rest
    team: spring-boot-actuator
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: aop-wms-rest
    team: spring-boot-actuator