apiVersion: apps/v1
kind: Deployment
metadata:
  name: aop-be-app-cv1-sit
  namespace: sit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aop-be-app-cv1-sit
  template:
    metadata:
      labels:
        app: aop-be-app-cv1-sit
    spec:
      containers:
        - name: aop-be-app-cv1-sit
          image: dtgsu1cv1cr01.azurecr.io/aop-be-app-cv1-sit:latest
          ports:
            - containerPort: 8080