apiVersion: apps/v1
kind: Deployment
metadata:
  name: aop-be-app-cv1-sit
  namespace: sit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aop-be-app-cv1-sit
  template:
    metadata:
      labels:
        app: aop-be-app-cv1-sit
        team: spring-boot-actuator
    spec:
      containers:
        - name: aop-be-app-cv1-sit
          image: __REPLACE_BY_YQ__
          ports:
            - containerPort: 8080