spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: aop-wms-rest
    
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

server:
  port: 8080

app:
  apim:
    webClientDomain: https://api.3601.com.hk/
