spring:
  application:
    name: wrapper
  webflux:
#    basePath: /v1/${spring.application.name}
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 8080
logging:
  level:
    com:
      agba: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG
#    org:
#      springframework:
#        data:
#          r2dbc: DEBUG
  file:
    path: "@project.build.directory@/logs"
    name: ${spring.application.name}
#app:
#  maxInMemorySize: 104857600 #100*1024*1024=100MB
#  microservice:
#    apim:
#      subscriptionKey: 4a07818d6a79410d8880864825426c94
#      basePath: /sit/op/clientPortal/v1

app:
  apim:
    webClientDomain: https://api.3601.com.hk/
    subscriptionKey: cd563a7eaace409a8cbce2a75aaa336b
